spring.application.name=shelfyn
spring.datasource.url=jdbc:postgresql://localhost:5432/Shelfyn
spring.datasource.username=postgres
spring.datasource.password=250601
spring.datasource.driver-class-name=org.postgresql.Driver